# Generated by Django 5.1.4 on 2024-12-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descroption',
            new_name='description',
        ),
    ]
