# Generated by Django 5.1.4 on 2024-12-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_title_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prepariion_time',
            new_name='preparation_time',
        ),
    ]
