# Generated by Django 5.1.4 on 2024-12-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_prepariion_time_recipe_preparation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preaparation_time_unit',
            new_name='preparation_time_unit',
        ),
    ]
