# Generated by Django 5.1.4 on 2024-12-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_preaparation_time_unit_recipe_preparation_time_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.TimeField(),
        ),
    ]
